# Generated by Django 6.0.1 on 2026-04-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
